# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Data-Driven Macromolecular Structure Solution @ LiU
email: nicholas.pearce (at) liu.se
description: >- # this means to ignore newlines until "baseurl:"
  The D3MS group is situated at Linköping University and develops novel methods 
  for modelling and analysing experimental macromolecular structures, with a particular 
  focus on flexibility and dynamics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nicholas_pearce
github_username: nicholas-pearce

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-timeago

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

paginate: 10
paginate_path: "/blog/page:num"

date_format: "%b %-d, %Y"

jekyll_timeago:
  depth: 1

collections_dir: collections

collections: 
  publications:
    output: false
  members:
    output: false
  projects:
    output: true
  vacancies:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "projects" # a collection in your site, in plural form
    values:
      layout: "project"
  - 
    scope: 
      path: ""
      type: "vacancies"
    values: 
      n_postdocs: 0
      n_phds: 0
